# This workflow generates PDFs with the differences between two PCBs or schematics.
# Recursive git submodules aren't supported (submodules inside submodules)

# To use this workflow in your own repo you need to edit the environment variables in the env: section
# below.
name: "KiBot - Generate PCB or Schematic Diff"

on:
  push:
    paths:
      - "**.kicad_sch"
      - "**.kicad_pcb"
  pull_request:
    paths:
      - "**.kicad_sch"
      - "**.kicad_pcb"

jobs:
  Diff:
    env:
      # Set this to the base filename of your project.
      BaseFileName: 24bit-ADC-logger
      # Set this to the output folder for all of the generated files. Unless you have a very
      # good reason to change this you should leave it as KiBotOutput.
      OutputFolder: KiBotOutput
    runs-on: ubuntu-latest

    # These are all the steps that generate the files.
    steps:
      # Check out the files
      - uses: actions/checkout@v2

      # Actually run KiBot to generate all the files. The KiBot script used is
      # in the .kibot/release.kibot.yaml folder.
      - name: Generate schematic documentation
        uses: INTI-CMNB/KiBot@v2_k6
        with:
          config: .kibot/diff.kibot.yaml
          dir: ${{ env.OutputFolder }}
          schema: pcb/${{ env.BaseFileName }}.kicad_sch
          board: pcb/${{ env.BaseFileName }}.kicad_pcb

      # Archive all the artifacts from output and attach to the action's results.
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: diff
          path: ${{ env.OutputFolder }}/**
